### PR TITLE
Added support for Django 3, current django-debug-toolbar and Django REST framework

### PR DESCRIPTION
**Pull request by mikekeda**

### CODE REVIEW

**Comment by Mogost** [comment]
Hi @mikekeda. This is a great job. But I doubt that this PR will be merged.
I tried several times to contact @dmclain (via github/email) about #17 (all attempts failed).
If someone continues to use this package, then most likely you need to think about fork.

**Comment by mikekeda** [comment]
@Mogost I released this fork on PyPi - https://pypi.org/project/django-debug-toolbar-line-profiling/0.7.0/

**Comment by mikekeda** [comment]
closed in favor of #21

**Comment by mikekeda** [comment]
closed in favor of #21

**Pull request closed without merging**
